name: Swift

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
      
